### ISSUE TITLE
prerequisites

### ISSUE THREAD

**Issue by msreekm** [abisek/elf_elk_docker#1]
Do we need to install ELK stack separately ,not clear from the readme.

**Comment by MoMoneyRiches** [comment]
Hello msreekm

No you do not need to install the ELK stack separately because we Dockerized the stack for you, meaning once you do `make run` it will download the stack into a Docker container, via the Dockerfile, and run it.

But thanks for pointing that out, I will update the readme shortly.

**Comment by msreekm** [comment]
got it, thanks for the response.

**Comment by MoMoneyRiches** [comment]
No problem :smile:

**Comment by msreekm** [comment]
right now iam stuck with this error -
SFDC: tyring to authenticate client {:level=>:info}
The error reported is:
  authentication failure
make: **\* [resume] Error 1

does the host need to be the full oath url like       https://test.salesforce.com/services/oauth2/token or just  https://test.salesforce.com ? can i get more error details in some logs?

```
    # The host to use for OAuth2 authentication.
    host           => "https://test.salesforce.com"
```

**Comment by abisek** [comment]
Please leave that commented out (with '#' before the line). The 'host' field is useful for internal Salesforce developers.

**Comment by msreekm** [comment]
it was commented out, bit not working. I thought since I was trying to connect to sandbox instead of prod org , it was required, no?

**Comment by abisek** [comment]
@msreekm, you are right :) Updated the config with comments. It takes the default value "https://login.salesforce.com" if the config is commented out. For Sandbox instances, you need to use "https://test.salesforce.com". Appreciate the feedback and happy to help! Let us know how it goes.

**Comment by msreekm** [comment]
no luck ,getting the same authentication error- 
SFDC: tyring to authenticate client {:level=>:info}
The error reported is:
  authentication failure
make: **\* [resume] Error 1

i updated username,password,oauth client id, secret, and host values . Am I missing something? I don't see the oauth failure in my org, could it be that it is not taking the host entry and always hitting login.salesforce.com? 

 # === Required Fields ===

```
    # Input the username and password of your Force.com organization.
    username       => "XXX"
    password       => "xxx"

    # Id & Secret are values that are generated when you create a "Connected App."
    client_id      => "XXXXX"
    client_secret  => "XXXXX"


    # === Optional Fields ===
    # Only needed when your Force.com organization requires it.
    # security_token => ""

    # The host to use for OAuth2 authentication.
     host  => "https://test.salesforce.com"
```

**Comment by msreekm** [comment]
after going through the scripts, I understood the problem.

when you make changes to sfdc_elf.config ,you need to make remove and make start for the changes to push again to docker container. Now it works when the host is commented out ,connects to a free developer edition (login.salesforce.com).
when I change host to https://test.salesforce.com to connect to another sandbox, gets the below error- can you document what should be the value for host for sandbox? 

SFDC: tyring to authenticate client {:level=>:info}
The error reported is:
  initialize: name or service not known

**Comment by abisek** [comment]
@msreekm I believe host should be "test.salesforce.com" without the "https://" prefix. I'll try to verify it tomorrow as soon as I get a chance and then update the documentation. Appreciate your patience and feedback!

-Abhishek

**Comment by msreekm** [comment]
test.salesforce.com worked :)  created a pull request https://github.com/abisek/elf_elk_docker/pull/2

**Comment by Shivakarasani** [comment]
Makefile:8: recipe for target 'run' failed

Facing this issue while pulling
